# Generated by Django 5.0.3 on 2024-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
