# Generated by Django 5.0.3 on 2024-03-20 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0004_orderitems_orders_profile_register_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shophouse.categories'),
        ),
    ]
