# Generated by Django 5.0.3 on 2024-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0005_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='price',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='title',
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
