# Generated by Django 5.0.3 on 2024-03-26 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0008_product_category_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('UserName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shophouse.profile')),
            ],
            options={
                'ordering': ['UserName'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('address', models.TextField(default='')),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shophouse.customer')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shophouse.login')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shophouse.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
