# Generated by Django 5.0.3 on 2024-03-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0009_customer_order_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_business', models.TextField()),
                ('type_of_business', models.TextField()),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.TextField()),
                ('logo', models.ImageField(upload_to='shophouse/media/')),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
