# Generated by Django 5.0.3 on 2024-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0010_registerbusiness_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbusiness',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='registerbusiness',
            name='name_of_business',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='registerbusiness',
            name='type_of_business',
            field=models.CharField(max_length=120),
        ),
    ]
