# Generated by Django 5.0.3 on 2024-03-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0011_alter_registerbusiness_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerbusiness',
            name='logo',
        ),
    ]
