# Generated by Django 5.0.3 on 2024-04-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0013_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(),
        ),
    ]
